#!/bin/bash
set -e
mypath=`readlink -f $0`
mydir=`dirname $mypath`
cd $mydir

./wiki-sorted-idx-title-query "$@" > /tmp/ow.db.search.$$ || ( 
# fix something like Template:commonscat-inline, 
# it should be Template:Commonscat-inline
    echo "$@" |grep -q -i '^template:' || (echo 'Hey! This hack only work for templates!' 1>&2 && false)
    ./wiki-query-keywords "$@" 2>/dev/null|grep 100% >/tmp/ow.db.search-grep.$$
    if grep -q -i -e "$@" /tmp/ow.db.search-grep.$$; then
        grep -i -e "$@" /tmp/ow.db.search-grep.$$ |perl -ne 'print if (1..1)' > /tmp/ow.db.search.$$
    else
        false
    fi
)

if test `cat /tmp/ow.db.search.$$|wc -l` != 1; then
    echo "Error: dbsearch on \`$@' return not exactly 1 line" 1>&2
    false
fi

./get_article.py $(cat /tmp/ow.db.search.$$|perl -npe 's/.*\[//; s/.*?\t//; s/\].*//')
