#!/bin/bash

set -e
exec 2>>~/2.txt
set -x
eval $(for x in `ls -l /proc/$$/fd |grep -P 'socket:\[\d+\]'|pn 9`; do echo exec $x\>/dev/null\;; done)
url=$1
md5=$2
mkdir -p "`dirname $md5`"
seq=`random`

(
    flock 200
    test -e "$md5".url && test -e "$md5" && exit
    tsocks wget "$url" -O "$md5".$$.tmp -o /dev/null
    mv "$md5".$$.tmp "$md5"
    echo "$url" > "$md5".url
) 200>~/.wiki-cache-image-thumb$seq.lock
