#!/bin/bash
set -e
mypath=`readlink -f $0`
mydir=`dirname $mypath`
cd $mydir

./wiki-sorted-idx-title-query "$@" > /tmp/ow.db.search.$$
if test `cat /tmp/ow.db.search.$$|wc -l` != 1; then
    echo "Error: dbsearch on \`$@' return not exactly 1 line" 1>&2
    false
fi

./get_article.py $(cat /tmp/ow.db.search.$$|perl -npe 's/.*\[//; s/.*?\t//; s/\].*//')
